FROM ubuntu:19.04

RUN apt-get update && apt-get install -y flang-7 clang-7 binutils perl make git python python-setuptools python-wheel unzip zip cpp liburi-perl wget

RUN groupadd -g $GID $GROUP
RUN useradd -g $GID -u $UID $USER

USER $USER
