FROM ubuntu:16.04

RUN apt-get update && apt-get install -y gcc-mingw-w64 gfortran-mingw-w64 perl make git python python-setuptools python-wheel unzip zip cpp liburi-perl

RUN groupadd -g $GID $GROUP
RUN useradd -g $GID -u $UID $USER

USER $USER
