# Top-level makefile for building the shared library dependencies.

RPNPY_SRCDIR=$(PWD)/..
RPNPY_BUILDDIR=$(PWD)/..
BUILDDIR=$(PWD)

include include/libs.mk

all: $(LIBRMN_SHARED) $(LIBDESCRIP_SHARED) $(LIBBURPC_SHARED)

