PLATFORM = local
PUBLIC_INCLUDES = $(PROJECT_ROOT)/librmn-$(LIBRMN_VERSION)/PUBLIC_INCLUDES
GCC = gcc
GFORTRAN = gfortran
SHAREDLIB_SUFFIX = so
RPN_MACRO_DIR = $(PROJECT_ROOT)/env-include/Linux_x86-64_gfortran
