language: python
sudo: false
matrix:
  include:
    - os: osx
      language: generic

before_install:
  - echo $TRAVIS_OS_NAME
  - brew install gcc
  - python --version # just to check
  - uname -a
  - pip install --upgrade pip setuptools wheel
  - set -o pipefail
script:
  # Build and install from source.
  - make sdist
  - pip install wheelhouse/eccc_rpnpy-*.zip -V
  # Run some basic checks to see if shared libraries can be loaded.
  - make clean
  - python -c "from rpnpy.librmn import librmn; print (librmn)"
  - python -c "from rpnpy.vgd import libvgd; print (libvgd)"
  - python -c "from rpnpy.burpc import libburpc; print (libburpc)"
  # Run some unit tests.
  - wget ftp://ccrp.tor.ec.gc.ca/pub/MNeish/wheelhouse/eccc_rpnpy_tests-2.1b3.zip -P wheelhouse/
  - pip install wheelhouse/eccc_rpnpy_tests-2.1b3.zip
  - rpy.tests
  # Try native build.
  - make native
  - ls -lh wheelhouse/

