language: python
sudo: false
matrix:
  include:
    - os: osx
      language: generic
env:
  - HOMEBREW_NO_AUTO_UPDATE=1
before_install:
  - echo $TRAVIS_OS_NAME
  - python --version # just to check
  - uname -a
  - pip install --upgrade pip
install:
  - brew uninstall --ignore-dependencies gcc
script:
  - pip install --upgrade numpy
  - pip install fstd2nc
  - wget https://collaboration.cmc.ec.gc.ca/science/ssm/afsisio_1.0u_all.ssm
  - tar -xzvf afsisio_1.0u_all.ssm
  - fstd2nc afsisio_1.0u_all/./data/datafiles/constants/ozoclim_Fortuin_Kelder1998 test.nc -f --exclude=i
  - python -c "import netCDF4 as nc; print (nc.Dataset('test.nc'))"

