language: python
sudo: false
matrix:
  include:
    - os: osx
      # Build for macOS 10.11
      osx_image: xcode7.3
      language: generic

before_install:
  - echo $TRAVIS_OS_NAME
  - brew update && brew upgrade && brew install gcc
  - python --version # just to check
  - uname -a
  - pip install --upgrade pip setuptools wheel
script:
  # Build a native wheel.
  - make clean && make native
  - ls -lh wheelhouse/
  # Install and test it (with no gcc or gfortran system libraries installed).
  - brew uninstall gcc
  - pip install wheelhouse/fstd2nc_deps-*.whl -V
  - python -c "import fstd2nc_deps; from rpnpy.librmn import librmn; print (librmn)"
  - python -c "import fstd2nc_deps; from rpnpy.vgd import libvgd; print (libvgd)"
  - python -c "import fstd2nc_deps; from rpnpy.burpc import libburpc; print (libburpc)"
  - pip install --no-deps fstd2nc
  - pip install netcdf4 numpy
  - wget https://collaboration.cmc.ec.gc.ca/science/ssm/afsisio_1.0u_all.ssm
  - tar -xzvf afsisio_1.0u_all.ssm
  - fstd2nc afsisio_1.0u_all/./data/datafiles/constants/irtab5_std test.nc

