FROM ubuntu:16.04

RUN apt-get update && apt-get install -y make python virtualenv wget

RUN groupadd -g $GID $GROUP || true
RUN useradd -g $GID -u $UID $USER

RUN apt-get update && apt-get install -y patch python-setuptools python-wheel
RUN apt-get update && apt-get install -y gfortran

USER $USER
